sudo: required

language: bash

services:
  - docker

before_install:
  - docker -v

script:
  - test/test_with_docker.sh

env:
  - IMAGE="ubuntu:16.04"
  - IMAGE="fedora:28"
  - IMAGE="debian:8"
  - IMAGE="centos:7"
  - IMAGE="debian:9"
  - IMAGE="ubuntu:18.04"
